//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 05:09:10 PM EST 
//


package edu.sample.soap.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConsumerLoan" type="{http://www.soap.sample.edu/jaxb}ConsumerLoan"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "consumerLoan"
})
@XmlRootElement(name = "PostConsumerLoanRequest")
public class PostConsumerLoanRequest {

    @XmlElement(name = "ConsumerLoan", required = true)
    protected ConsumerLoan consumerLoan;

    /**
     * Gets the value of the consumerLoan property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerLoan }
     *     
     */
    public ConsumerLoan getConsumerLoan() {
        return consumerLoan;
    }

    /**
     * Sets the value of the consumerLoan property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerLoan }
     *     
     */
    public void setConsumerLoan(ConsumerLoan value) {
        this.consumerLoan = value;
    }

}
