server.port: 9090

camel.springboot.shutdownTimeout: 2

spring:
 profiles: 
  active: dev
  
---
spring:
 profiles: dev
 
 
startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output

---
spring:
 profiles: stage
 
startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output
 
message: Stage Environment

---

spring:
 profiles: prod
 
startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output
 
 